// ITPassport Adventure - collection items (auto-generated from items-*.json)
// rarity: 1..5   effect: charm bonus (rarity 4+ only)   avatar: usable as player avatar

const ITEMS = [
{id:"retro-floppy",name:"3.5インチフロッピーディスク",emoji:"💾",rarity:1,category:"記録メディア",flavor:"容量1.44MB。当時はこれで卒業論文が入ると信じられていた。書き込み中の小さな異音で心臓が止まりかけた。",series:"media-history",seriesOrder:1,effect:null,avatar:false},
{id:"retro-mo",name:"MOディスク",emoji:"📀",rarity:3,category:"記録メディア",flavor:"光と磁気の合わせ技で数百MB。カートリッジの重みが「これは本気のデータだ」と語っていた。読める機械はもう家にない。",series:"media-history",seriesOrder:2,effect:null,avatar:false},
{id:"retro-cdr",name:"CD-Rの生ディスク",emoji:"💿",rarity:1,category:"記録メディア",flavor:"一枚焼くのに十数分、途中で他の作業をすると失敗する繊細な相棒。焼き損じの銀色は今もどこかの引き出しで眠っている。",series:"media-history",seriesOrder:3,effect:null,avatar:false},
{id:"retro-cloud",name:"クラウドストレージ",emoji:"☁️",rarity:2,category:"記録メディア",flavor:"円盤も差込口もいらない時代。かわりに「同期中」の輪がいつまでも回り続ける。棚は空いたが、心のどこかは埋まらない。",series:"media-history",seriesOrder:4,effect:null,avatar:false},
{id:"retro-acoustic",name:"音響カプラ",emoji:"☎️",rarity:4,category:"通信機器",flavor:"受話器を専用の枕にそっと寝かせると、機械同士が悲鳴のような音で挨拶を始める。家族の通話はもちろんそこで終了した。",series:"network-dawn",seriesOrder:1,effect:{type:"chest",value:0.05,label:"宝箱の出現率 +5%"},avatar:false},
{id:"retro-modem",name:"ダイヤルアップモデム",emoji:"📞",rarity:2,category:"通信機器",flavor:"接続の音はピーとガー。深夜料金が始まる時刻を秒単位で覚えていた。途中で親が受話器を上げると世界が切れた。",series:"network-dawn",seriesOrder:2,effect:null,avatar:false},
{id:"retro-adsl",name:"ADSLモデム",emoji:"🔌",rarity:2,category:"通信機器",flavor:"常時接続という魔法。つなぐたびに鳴っていた音が消え、ネットは行き先ではなく空気になった。電話代の心配も消えた。",series:"network-dawn",seriesOrder:3,effect:null,avatar:false},
{id:"retro-wifi",name:"無線LANルーター",emoji:"📶",rarity:1,category:"通信機器",flavor:"線が消えて家中どこでもつながる。ただし置き場所で速度が変わるので、いつのまにか家具の配置まで電波が決めていた。",series:"network-dawn",seriesOrder:4,effect:null,avatar:false},
{id:"retro-corememory",name:"磁気コアメモリ",emoji:"🧶",rarity:5,category:"記録メディア",flavor:"米粒ほどの輪に細い線を手で通して編み上げた記憶装置。容量はわずか数キロバイト。誰かの指先が、たしかにここに宿っている。",series:null,seriesOrder:null,effect:{type:"xp",value:0.2,label:"獲得XP +20%"},avatar:false},
{id:"retro-punchcard",name:"パンチカードの束",emoji:"🗂️",rarity:4,category:"記録メディア",flavor:"穴の位置が文字であり命令だった。輪ゴムが切れて床にばらまいた瞬間、その日の残業が確定する魔法の紙束。",series:null,seriesOrder:null,effect:{type:"coin",value:0.2,label:"獲得コイン +20%"},avatar:false},
{id:"retro-luggable",name:"弁当箱型ポータブルPC",emoji:"🧳",rarity:4,category:"PC本体",flavor:"重さ十数キロを堂々と「携帯用」と言い切った気概の一台。持ち運ぶたび腕が鍛えられ、机に置くと机のほうが軋んだ。",series:null,seriesOrder:null,effect:{type:"xp",value:0.1,label:"獲得XP +10%"},avatar:false},
{id:"retro-brownmonitor",name:"ブラウン管ディスプレイ",emoji:"📺",rarity:3,category:"入出力機器",flavor:"奥行きも重さも堂々たる箱型。冬は暖房代わりになり、消した瞬間の静電気で腕の毛が立った。画面の隅は少し丸かった。",series:null,seriesOrder:null,effect:null,avatar:true},
{id:"retro-dotmatrix",name:"ドットインパクトプリンタ",emoji:"🖨️",rarity:3,category:"入出力機器",flavor:"ギーコギーコと横に往復しながら文字を叩き込む。連続用紙の両端を切り離す作業には、なぜか妙な達成感があった。",series:null,seriesOrder:null,effect:null,avatar:false},
{id:"retro-pager",name:"小型無線呼び出し機",emoji:"📟",rarity:3,category:"通信機器",flavor:"数字だけで気持ちを伝える技術がやたらと磨かれた小さな箱。「0840」で朝の挨拶が済んだ、贅沢に不便な時代の証。",series:null,seriesOrder:null,effect:null,avatar:false},
{id:"retro-tapedrive",name:"カセットテープ記録装置",emoji:"📼",rarity:3,category:"記録メディア",flavor:"遊びたいゲームを読み込むのに十分待つ。途中でカウンターが止まれば全部やり直し。あの待ち時間に想像力が育っていた。",series:null,seriesOrder:null,effect:null,avatar:false},
{id:"retro-ballmouse",name:"ボール式マウス",emoji:"🖱️",rarity:2,category:"入出力機器",flavor:"動きが渋くなったら裏蓋を開け、転がる玉と軸のホコリをこそげ取る。手入れを欠かすと機嫌を損ねる、生き物めいた相棒。",series:null,seriesOrder:null,effect:null,avatar:true},
{id:"retro-flipphone",name:"折りたたみ式携帯電話",emoji:"📱",rarity:2,category:"通信機器",flavor:"パチンと閉じる音で会話を終える爽快感。着信音を自分で一音ずつ打ち込み、赤外線で友だちに送りつけていた季節。",series:null,seriesOrder:null,effect:null,avatar:true},
{id:"retro-pda",name:"手のひらサイズの電子手帳",emoji:"🗒️",rarity:2,category:"携帯端末",flavor:"手のひらの中で予定を管理する未来的な板。細い棒で画面をつつき、結局は紙の手帳より遅かった。愛おしい遠回り。",series:null,seriesOrder:null,effect:null,avatar:false},
{id:"retro-scanner",name:"フラットベッドスキャナ",emoji:"🖼️",rarity:2,category:"入出力機器",flavor:"蓋を閉じるとまぶしい光が横切って、紙の写真が画面の中の絵に変わる。厚みのある本を写すと真ん中がいつも暗く沈んだ。",series:null,seriesOrder:null,effect:null,avatar:false},
{id:"retro-mousepad",name:"マウスパッド",emoji:"🟦",rarity:1,category:"周辺小物",flavor:"布の上でだけ本気を出せた玉入りマウスの専用舞台。使い込むと真ん中だけ毛羽立って、そこが定位置の証になった。",series:null,seriesOrder:null,effect:null,avatar:false},
{id:"retro-numpad",name:"外付けテンキー",emoji:"🔢",rarity:1,category:"入出力機器",flavor:"数字を打つためだけに机の隅へ居座る小さな相棒。表計算の入力速度が倍になり、電卓は静かに引き出しへ移住した。",series:null,seriesOrder:null,effect:null,avatar:false},
{id:"retro-lancable",name:"LANケーブル",emoji:"🔗",rarity:1,category:"通信機器",flavor:"青くて硬くて、必ず必要な長さより少し短い。机の裏で他の線と絡み合い、抜くときはたいてい別の線も一緒に抜けた。",series:null,seriesOrder:null,effect:null,avatar:false},
{id:"retro-airduster",name:"エアダスター",emoji:"💨",rarity:1,category:"周辺小物",flavor:"隙間のホコリを吹き飛ばす頼れる一本。使いすぎて缶が冷たくなり、勢いが落ちるまで掃除に熱中してしまう魔力がある。",series:null,seriesOrder:null,effect:null,avatar:false},
{id:"retro-cdsleeve",name:"不織布のディスクケース",emoji:"📁",rarity:1,category:"周辺小物",flavor:"円盤を薄く収める白い袋。棚が一気に片づく代わりに、どの袋に何が入っているか永遠に分からなくなる巧妙な仕組み。",series:null,seriesOrder:null,effect:null,avatar:false},
{id:"office-sticky-password",name:"パスワードが書かれた付箋",emoji:"🏷️",rarity:1,category:"職場の遺物",flavor:"ディスプレイの縁に貼られている。研修を受けた翌日、貼る場所が裏側に変わった。それが唯一の対策だった。",series:null,seriesOrder:null,effect:null,avatar:false},
{id:"office-printer-jam",name:"紙が詰まったプリンタ",emoji:"📃",rarity:1,category:"トラブルの記録",flavor:"画面には「用紙を取り除いてください」。前も後ろも開けてみたが、取り除くべき紙はどこにも見つからない。",series:null,seriesOrder:null,effect:null,avatar:false},
{id:"office-slow-pc",name:"起動に九分かかるPC",emoji:"💻",rarity:1,category:"職場の遺物",flavor:"電源を押してから給湯室でお茶を淹れて戻ると、ちょうどログイン画面が出る。時間の使い方だけは上手くなった。",series:null,seriesOrder:null,effect:null,avatar:false},
{id:"office-cable-nest",name:"机の裏のケーブル束",emoji:"🕸️",rarity:1,category:"職場の遺物",flavor:"十二本のうち一本は、どこにもつながっていない。それがどれなのか、確かめる勇気を持つ者はまだ現れない。",series:null,seriesOrder:null,effect:null,avatar:false},
{id:"office-final-filename",name:"最終版_修正2_確定",emoji:"📄",rarity:1,category:"職場の遺物",flavor:"共有フォルダでいちばん新しいのは、なぜか「最終版」ではない。名前で管理していた時代の、静かな敗北の記録。",series:null,seriesOrder:null,effect:null,avatar:false},
{id:"office-late-invite",name:"開始一分前の会議招待",emoji:"📩",rarity:1,category:"会議の産物",flavor:"件名は「少しだけご相談」、開始は一分後。少しだけで済んだ会議を、これまで一度も見たことがない。",series:null,seriesOrder:null,effect:null,avatar:false},
{id:"office-night-call",name:"定時二分前の内線",emoji:"📴",rarity:1,category:"トラブルの記録",flavor:"十七時五十八分に鳴る。「今朝から変だったんですけど、今いいですか」。今朝から、のところが引っかかる。",series:"night-shift",seriesOrder:1,effect:null,avatar:false},
{id:"office-key-notebook",name:"前任者のパスワード手帳",emoji:"📓",rarity:1,category:"職場の遺物",flavor:"引き継ぎ資料はこの一冊きり。最後の三ページだけ、本人にしか読めない筆跡でびっしり埋まっている。",series:"key-keeping",seriesOrder:1,effect:null,avatar:false},
{id:"office-worn-keyboard",name:"刻印が消えたキーボード",emoji:"⌨️",rarity:2,category:"職場の遺物",flavor:"消えているのはEとAとEnter。持ち主だけが正確に打てる、世界に一台しかない入力装置に育っていた。",series:null,seriesOrder:null,effect:null,avatar:false},
{id:"office-whiteboard-keep",name:"消さないでのホワイトボード",emoji:"📋",rarity:2,category:"会議の産物",flavor:"隅に赤字で「消さないで」。書いた本人は二年前に異動し、残った図の意味を説明できる人はもういない。",series:null,seriesOrder:null,effect:null,avatar:false},
{id:"office-sinking-chair",name:"静かに沈む椅子",emoji:"💺",rarity:2,category:"職場の遺物",flavor:"座って三分で高さが下がりはじめる。会議の後半、発言の説得力だけが物理的に低くなっていく。",series:null,seriesOrder:null,effect:null,avatar:false},
{id:"office-fax-active",name:"まだ現役のFAX",emoji:"📠",rarity:2,category:"職場の遺物",flavor:"電子化の検討を三年続けている。その三年のあいだも、いちばん確実に相手へ届く手段であり続けている。",series:null,seriesOrder:null,effect:null,avatar:false},
{id:"office-screenshot-manual",name:"画面写真だらけの手順書",emoji:"📚",rarity:2,category:"職場の遺物",flavor:"一手順ごとに画面写真が貼られている。写っているのは三世代前の画面で、そのボタンはもう存在しない。",series:null,seriesOrder:null,effect:null,avatar:false},
{id:"office-night-drink",name:"三本目の栄養ドリンク",emoji:"🥤",rarity:2,category:"トラブルの記録",flavor:"一本目は景気づけ、二本目は惰性、三本目は儀式。机に並んだ空き瓶が、そのまま作業ログになっている。",series:"night-shift",seriesOrder:2,effect:null,avatar:false},
{id:"office-key-sheet",name:"鍵のかかっていない一覧表",emoji:"🔓",rarity:2,category:"職場の遺物",flavor:"表計算ソフト製、ファイル名は「一覧_最新_確定」。誰でも開ける場所にあり、鍵だけがかかっていない。",series:"key-keeping",seriesOrder:2,effect:null,avatar:false},
{id:"office-orphan-macro",name:"作者不明のマクロ",emoji:"📊",rarity:3,category:"職場の遺物",flavor:"二十年、毎月正しい数字を出し続けている。作者は退職済み。中を開いた人は、たいてい静かに閉じ直す。",series:null,seriesOrder:null,effect:null,avatar:false},
{id:"office-premeeting",name:"会議のための会議",emoji:"🗓️",rarity:3,category:"会議の産物",flavor:"本会議の進め方を決めるための会議。九十分かけて決まったのは、次に集まる日程だけだった。",series:null,seriesOrder:null,effect:null,avatar:false},
{id:"office-desk-sage",name:"なんでも知っている隣の席",emoji:"🧑‍🏫",rarity:3,category:"職場の伝説",flavor:"手順書に載っていないことを全部知っている。異動の噂が流れるたび、部署全体が静かにざわつきだす。",series:null,seriesOrder:null,effect:null,avatar:true},
{id:"office-night-log",name:"何も書かれていないログ",emoji:"📜",rarity:3,category:"トラブルの記録",flavor:"深夜二時。エラーは一件も出ていない。出ていないというその事実が、この夜でいちばん恐ろしかった。",series:"night-shift",seriesOrder:3,effect:null,avatar:false},
{id:"office-key-approval",name:"三度戻ってきた稟議",emoji:"📑",rarity:3,category:"会議の産物",flavor:"管理ツール導入の稟議書。費用で戻され、運用で戻され、三度目に一行足したらあっさり判子が並んだ。",series:"key-keeping",seriesOrder:3,effect:null,avatar:false},
{id:"office-reply-all-storm",name:"全員に返信の連鎖",emoji:"📨",rarity:4,category:"トラブルの記録",flavor:"「宛先から外してください」が全員に返信で届く。「返信を止めてください」も、全員に返信で届く。",series:null,seriesOrder:null,effect:{type:"chest",value:0.05,label:"宝箱の出現率 +5%"},avatar:false},
{id:"office-night-firstrain",name:"始発を待つ担当者",emoji:"😪",rarity:4,category:"職場の伝説",flavor:"復旧は四時四十七分、目撃者はゼロ。改札が開くのを待つベンチで、なぜか少し笑ってしまった。",series:"night-shift",seriesOrder:4,effect:{type:"xp",value:0.1,label:"獲得XP +10%"},avatar:true},
{id:"office-key-mfa",name:"三十秒で消える六桁",emoji:"🔐",rarity:4,category:"職場の遺物",flavor:"三十秒ごとに新しくなる六桁。覚えるものが一つに減った日、鍵の管理は人の記憶から静かに離れた。",series:"key-keeping",seriesOrder:4,effect:{type:"coin",value:0.15,label:"獲得コイン +15%"},avatar:false},
{id:"office-immortal-server",name:"止められないサーバー",emoji:"🖥️",rarity:5,category:"職場の伝説",flavor:"机の下で回り続けている。手書きのラベルには「絶対に電源を切らないで」とだけ。用途を知る人はもういないが、止めた日には必ず何かが動かなくなる。",series:null,seriesOrder:null,effect:{type:"xp",value:0.18,label:"獲得XP +18%"},avatar:false},
{id:"chara-plan",name:"計画の精霊プラン",emoji:"🧚",rarity:1,category:"PDCAの精霊",flavor:"まず地図を描く精霊。目標と、そこへ至る手順と、いつ誰がやるかを決めてから動く。ここが雑だと、あとの三人が苦労する。",series:"pdca-spirits",seriesOrder:1,effect:null,avatar:true},
{id:"chara-do",name:"実行の精霊ドゥ",emoji:"🐝",rarity:1,category:"PDCAの精霊",flavor:"計画を手足で形にする働き者。おしゃべりは苦手で、とにかく動く。決めたとおりにやるからこそ、あとで結果を比べられる。",series:"pdca-spirits",seriesOrder:2,effect:null,avatar:true},
{id:"chara-check",name:"評価の精霊チェック",emoji:"🧐",rarity:2,category:"PDCAの精霊",flavor:"やった結果と計画を並べて、どこがどれだけずれたかを測る。ほめもせず責めもせず、ただ事実だけを書き留めていく。",series:"pdca-spirits",seriesOrder:3,effect:null,avatar:true},
{id:"chara-act",name:"改善の精霊アクト",emoji:"🧞",rarity:2,category:"PDCAの精霊",flavor:"ずれの原因に手を入れ、次の計画へ渡す精霊。直して終わりではなく、直した先をまた回す。四人はぐるぐると輪になっている。",series:"pdca-spirits",seriesOrder:4,effect:null,avatar:true},
{id:"chara-confidentiality",name:"機密性の目隠しザル",emoji:"🙈",rarity:2,category:"セキュリティの三柱",flavor:"許された者以外には、絶対に中身を見せないサル。のぞき見をされないように鍵をかけ、暗号にして隠しておくのが仕事だ。",series:"security-pillars",seriesOrder:1,effect:null,avatar:true},
{id:"chara-integrity",name:"完全性の記録ゾウ",emoji:"🐘",rarity:2,category:"セキュリティの三柱",flavor:"預かった情報を一字も違わず覚えているゾウ。誰かが勝手に書き換えたり壊したりすれば、すぐに気づいて元の姿を証明する。",series:"security-pillars",seriesOrder:2,effect:null,avatar:true},
{id:"chara-availability",name:"可用性の眠らぬフクロウ",emoji:"🦉",rarity:3,category:"セキュリティの三柱",flavor:"使いたいときにいつでも使えるよう、夜も昼も止まらず見張る鳥。壊れても代わりが動くように、道も装置も二重に備えている。",series:"security-pillars",seriesOrder:3,effect:null,avatar:true},
{id:"chara-vulnerability",name:"脆弱性の影",emoji:"👻",rarity:3,category:"セキュリティの三柱",flavor:"守りのわずかな穴やほころびに、すきま風のように入り込む。狙う者と穴がそろった時だけ、被害という形をとって現れる。",series:"security-pillars",seriesOrder:4,effect:null,avatar:true},
{id:"chara-cash-cow",name:"金のなる木のウシ",emoji:"🐄",rarity:1,category:"ストラテジの島の住人",flavor:"よく売れる市場で大きな取り分を握っているが、その市場はもう伸びない。手をかけずとも乳を出し、他の事業の元手になる。",series:null,seriesOrder:null,effect:null,avatar:true},
{id:"chara-bug",name:"バグの虫",emoji:"🐛",rarity:1,category:"ソフトウェアの魔物",flavor:"作った本人が気づかないうちに紛れ込む、プログラムの誤り。テストで見つけて取り除く作業をデバッグと呼ぶ。まだ仲間がいる。",series:null,seriesOrder:null,effect:null,avatar:true},
{id:"chara-copyright",name:"著作権の署名グマ",emoji:"🐻",rarity:1,category:"ストラテジの島の番人",flavor:"文章や絵や曲が生まれたその瞬間に権利は生じる、と言い張るクマ。届け出も登録も要らない。無断のコピーだけは決して許さない。",series:null,seriesOrder:null,effect:null,avatar:true},
{id:"chara-cache",name:"キャッシュの木の実リス",emoji:"🐿️",rarity:1,category:"ハードウェアの仲間",flavor:"よく使うデータだけを手元の小さな穴にしまっておくリス。遠い倉庫まで取りに行かずに済むので、待ち時間がぐんと短くなる。",series:null,seriesOrder:null,effect:null,avatar:true},
{id:"chara-helpdesk",name:"ヘルプデスクの案内ネコ",emoji:"🐱",rarity:1,category:"サービスの窓口",flavor:"困った利用者がまず訪ねる、たったひとつの窓口。自分で答えられないことは、詳しい担当へきちんと引き継いでから見送る。",series:null,seriesOrder:null,effect:null,avatar:true},
{id:"chara-brainstorming",name:"ブレーンストーミングのカエル",emoji:"🐸",rarity:1,category:"会議室の住人",flavor:"思いついたことを片端から鳴き散らすカエル。人の案を否定せず、むしろ便乗して重ねていく。質より量、まずは数を出す。",series:null,seriesOrder:null,effect:null,avatar:true},
{id:"chara-agile",name:"アジャイルの駆けウサギ",emoji:"🐇",rarity:2,category:"開発の仲間",flavor:"小さく作ってすぐ見せ、返ってきた声で作り直す。それを短い期間で何度も繰り返す。仕様が変わっても平気な顔で跳ねている。",series:null,seriesOrder:null,effect:null,avatar:true},
{id:"chara-niche",name:"ニッチ戦略のヤドカリ",emoji:"🦀",rarity:2,category:"ストラテジの島の住人",flavor:"大きな相手が見向きもしない小さな貝殻をあえて選ぶ。市場を狭く絞る代わりに、そこでは誰にも負けない。小さいが王様だ。",series:null,seriesOrder:null,effect:null,avatar:true},
{id:"chara-critical-path",name:"クリティカルパスの綱渡りヤギ",emoji:"🐐",rarity:2,category:"プロジェクトの案内役",flavor:"作業をつないだ道のうち、いちばん長くて余裕がゼロの一本を歩く。ここが一日遅れれば、計画全体がそのまま一日遅れる。",series:null,seriesOrder:null,effect:null,avatar:true},
{id:"chara-swot",name:"SWOTの四眼賢者",emoji:"🧙",rarity:3,category:"ストラテジの島の賢者",flavor:"内側の強みと弱み、外側の機会と脅威。四つの目で同時に見て、自分と世の中の位置を一枚の表に描き出す。見立てを誤れば戦略も外れる。",series:null,seriesOrder:null,effect:null,avatar:true},
{id:"chara-dns",name:"DNSの名前引きインコ",emoji:"🦜",rarity:3,category:"ネットワークの精霊",flavor:"人が覚えやすい名前を、機械が使う数字の住所に言い換えてくれるインコ。この子が黙ると、あるはずの場所へたどり着けなくなる。",series:null,seriesOrder:null,effect:null,avatar:true},
{id:"chara-normalization",name:"正規化の整理アリ",emoji:"🐜",rarity:3,category:"データベースの住人",flavor:"同じ内容が何度も書かれた表を見ると、我慢できずに分け始めるアリ。重複を削り、矛盾やムダが起きない形に組み直していく。",series:null,seriesOrder:null,effect:null,avatar:true},
{id:"chara-firewall",name:"ファイアウォールの守炎竜",emoji:"🐲",rarity:4,category:"セキュリティの守護者",flavor:"内と外の境目に座り、行き交う通信を一つずつ確かめる竜。あらかじめ許された相手だけを通し、それ以外は炎で追い返す。",series:null,seriesOrder:null,effect:{type:"chest",value:0.05,label:"宝箱の出現率 +5%"},avatar:true},
{id:"chara-machine-learning",name:"機械学習の学びスライム",emoji:"👾",rarity:4,category:"テクノロジの塔の新参者",flavor:"与えられた例をたくさん食べるほど、規則を自分で見つけて賢くなる。やがて教わっていない問いにも、それらしく答えはじめる。",series:null,seriesOrder:null,effect:{type:"xp",value:0.1,label:"獲得XP +10%"},avatar:true},
{id:"chara-blockchain",name:"ブロックチェーンの連鎖蛇",emoji:"🐍",rarity:4,category:"テクノロジの塔の記録者",flavor:"取引の記録をひとかたまりにして、鎖のように前へつないでいく蛇。同じ台帳を皆で分け持つので、こっそり書き換えるのは至難。",series:null,seriesOrder:null,effect:{type:"coin",value:0.2,label:"獲得コイン +20%"},avatar:true},
{id:"chara-binary",name:"二進の女神ビナリア",emoji:"👸",rarity:5,category:"基礎理論の女神",flavor:"使う数字は0と1のふたつだけ。それだけで文字も音も映像も書き表す。この塔のすべての住人は、彼女の二進数の上に立っている。",series:null,seriesOrder:null,effect:{type:"xp",value:0.2,label:"獲得XP +20%"},avatar:true},
];

// Series: collecting all four reveals a short story
const ITEM_SERIES = [
{id:"media-history",name:"記録メディア進化史",emoji:"📀",itemIds:["retro-floppy","retro-mo","retro-cdr","retro-cloud"],story:["机の引き出しに、四角い相棒が一枚だけ。上書き保存のたびに小さく鳴く音が、その日の作業が確かに進んだしるしだった。まだ、データには手触りがあった。","やがて容量が足りなくなり、もっと重くて頼もしい円盤がやってきた。専用の機械を買い足した日、これで一生困らないと本気で思っていた。棚が一段、埋まった。","焼く、という言葉を覚えた。失敗した銀色が積み上がるほど、成功した一枚が誇らしい。友人に渡す円盤へ、油性ペンで下手な文字を書いていたあの頃。","気づけば棚は空っぽで、データは名前のない場所に浮かんでいる。どこにでもあって、どこにも置いていない。あの引き出しの重みだけが、まだ指に残っている。"],complete:"手のひらに乗る重さから、触れられない軽さへ。進化したのは容量ではなく、私たちがデータを信じる方法だったのかもしれない。それでも時々、あのカチャという音が聞きたくなる。"},
{id:"network-dawn",name:"つながる音の記憶",emoji:"📡",itemIds:["retro-acoustic","retro-modem","retro-adsl","retro-wifi"],story:["受話器を専用のくぼみに寝かせた瞬間、機械が耳障りな声で遠くの誰かを呼んだ。世界とつながる音は、決して美しくはなかった。それでも胸は高鳴った。","やがて線は直接つながるようになったが、音は残った。ピーガーという儀式のあと、深夜だけ許された安い時間に、画面が一行ずつ絵を描いていく。","ある日、待つ必要がなくなった。つなぐという動作そのものが消え、ネットは蛇口をひねれば出てくるものになった。あの音を懐かしむ暇さえなかった。","そして線までなくなった。家のどこにいてもつながる代わりに、つながった瞬間を知らせる音はもうどこにもない。静けさは、便利さの別名だった。"],complete:"つながるとは、かつて音のする出来事だった。今は当たり前すぎて誰も気づかない。あの耳障りなピーガーは、遠くへ手を伸ばす合図であり、待つことを知っていた時代の子守唄だ。"},
{id:"night-shift",name:"情シスの長い夜",emoji:"🌙",itemIds:["office-night-call","office-night-drink","office-night-log","office-night-firstrain"],story:["「今いいですか」の一言で、その日の予定は全部うしろに倒れた。話を聞くほど、これは今日は帰れないやつだと分かってくる。まず、深呼吸をした。","二本目を開けたころ、原因の候補は三つに絞られた。三つとも、確かめるには本番を止めなければならないものだった。腹をくくって、申請書を書いた。","深夜二時、ログは何も語らない。設定を一行だけ書き換えたのは、半年前の自分だった。誰も責める相手がいないのが、いちばんつらいところだ。","四時四十七分、画面がいつもの顔に戻った。報告メールを送って、始発を待つ。誰にも知られない夜が一つ、静かに終わっていった。"],complete:"記録に残るのは「復旧しました」の一行だけ。その裏に、空き瓶三本と、始発待ちのベンチと、少しの誇りがある。あの朝の空は、たしかに悪くなかった。"},
{id:"key-keeping",name:"鍵のしまい場所",emoji:"🔑",itemIds:["office-key-notebook","office-key-sheet","office-key-approval","office-key-mfa"],story:["引き継ぎの日、前任者は分厚い手帳を机に置いて「これで全部です」と笑った。本当に全部だったので、こちらはうまく笑えなかった。","手帳を表計算ソフトに写した。検索できて便利になった。便利になった分だけ、そのファイルは誰でも開ける共有フォルダに置かれてしまった。","さすがにこれはまずいと稟議を書いた。二度も戻され、三度目に「事故が起きる前に直したい」と一行足したら、判子はあっさり並んだ。","移行の日、覚えるパスワードは一つになった。あとは金庫の中と、三十秒で消える六桁が守ってくれる。手帳の役目はここで終わりだ。"],complete:"手帳は捨てずに、いちばん下の引き出しへしまった。あれがなければ何も始まらなかった。もう二度と開かなくていい、というのは、たぶん進歩なのだ。"},
{id:"pdca-spirits",name:"PDCAの四精霊",emoji:"🔄",itemIds:["chara-plan","chara-do","chara-check","chara-act"],story:["はじめに、計画の精霊が白紙に地図を描いた。まだ何も起きていない世界に、目指す場所と、そこへ向かう道順だけが引かれる。動き出すのは、まだ先の話だ。","実行の精霊が地図を持って歩き出した。書かれたとおりに、寄り道はせずに。やってみて初めて、地図には描かれていなかった坂や川が姿を見せる。","評価の精霊が二枚の紙を並べた。描いた地図と、実際に歩いた跡。重ならない場所こそが宝で、次にどこへ手を入れるべきかがそこに眠っている。","改善の精霊が地図を書き直した。坂には階段を、川には橋を。そして新しい地図を、また計画の精霊へ手渡す。輪が閉じ、そして同時に開いた。"],complete:"四精霊がそろい、輪が回りはじめた。計画し、実行し、評価し、改善する。一周ごとに地図は少し正しくなり、螺旋を描いて高く登っていく。終わりがないことが、この輪の強さだ。"},
{id:"security-pillars",name:"情報セキュリティの三柱と影",emoji:"🛡️",itemIds:["chara-confidentiality","chara-integrity","chara-availability","chara-vulnerability"],story:["はじめに宝は、見せないという約束で守られた。目隠しのサルが鍵を預かり、許された者の名だけを覚えた。けれど、隠すだけではまだ足りなかった。","次に、ゾウが宝の姿を丸ごと覚えた。誰かが一文字でも書き換えれば、たちまち声をあげる。隠され、正しく保たれた宝。それでも、まだ足りない。","三本目の柱はフクロウだった。宝は、使いたいときに使えなければ意味がない。必ず開く扉を、彼は眠らずに見張り続けた。守りは完成した——はずだった。","柱と柱のあいだに、細い隙間が残っていた。影はそこから入り込む。狙う者がその隙間を見つけたときに、はじめて被害は形になる。三柱は影を知り、自らの弱点を知った。"],complete:"機密性、完全性、可用性。三本の柱は、影が指し示した隙間を埋めるためにこそ立っている。守りとは完成する城ではなく、隙間を探し続ける営みなのだと、この四体は教えてくれる。"},
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = { ITEMS, ITEM_SERIES };
}
